# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TMDB' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TMDB
  # Pod for IQ Keyboard Manager Swift
  pod 'IQKeyboardManagerSwift'
  
  # Pod for Reactive Programming
  pod 'RxSwift'
  pod 'RxCocoa'
  
  # Pod for networking
  pod 'Alamofire'
  
  # Pod for parsing
  pod 'SwiftyJSON'
  
  # Pod for loading
  pod 'MBProgressHUD'
  
  # Pod for images
  pod 'Kingfisher'
  
  # Pod for local DB
  pod 'RealmSwift'

  target 'TMDBTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TMDBUITests' do
    # Pods for testing
  end

end
